### ISSUE TITLE
Clicking Purchase Button doesn't navigate to correct route

### ISSUE THREAD

**Issue by BhaveshG-22** [mahdi-Eth/BookTown-Proj#1]
code of purchase button in /Cart/index.html -> <button onclick="window.open('http://127.0.0.1:5500/PaymentPage/index.html','_self','resizable=yes')" type="button" class="btn btn-danger">Go To Payment Page</button>
needs to be updated to render correct files and route.

**Comment by mahdi-eth** [comment]
Hi, thanks for sharing. But in both local and live versions it does go to payment page successfully. Could you please provide more information so I can fix the problem?

**Comment by BhaveshG-22** [comment]
On line 65 of ( Home-Page/index.html ) the span redirects to local host route -->         
`<span onclick="window.open('http://127.0.0.1:5500/Cart/index.html','_self','resizable=yes')">`
instead it should redirect to **Cart route**  i.e `<span onclick="window.open('https://booktown-4ix2.onrender.com/Cart/index.html')">`
hope I was able to understand you issue.

![Screenshot 2023-04-02 105811](https://user-images.githubusercontent.com/107833962/229361076-ca510a0f-bc46-4de5-9bab-216ef7d2362b.png)

**Comment by mahdi-eth** [comment]
Thank you for bringing the issue to my attention. Your feedback helped me identify and fix the problem quickly. I appreciate your contribution to improving the quality of my work.
